In [1]:
import numpy as np

### Массив одного типа

In [2]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

### Если в массиве есть значения другого типа, то numpy попытаеся преобразовать к более широкому типу

In [3]:
np.array([1.3, 4, 5, 8])

array([1.3, 4. , 5. , 8. ])

### Необходимо явно задавать тип данных в массиве!!!

In [4]:
np.array([1, 2, 30], dtype='float32')

array([ 1.,  2., 30.], dtype=float32)

### Преобразование вложенных списков в многомерный массив

In [6]:
np.array([range(i, i+3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

# Создание массивов с нуля

In [8]:
np.zeros(10, dtype=int) #массив 10 целых чисел, заполненный нулями

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
np.ones((3, 5), dtype=float) #массив 3*5 значений с плав точкой, заполненный единицами

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.full((3, 5), 3.14) #массив 3*5, заполненный числами 3,14

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [16]:
np.arange(0, 20, 2) #заполненный массив по принципу создания списка функцией range(start, finish, step).
#Линейная последовательность

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [19]:
np.linspace(0, 1, 5) #массив из 5-ти значений, равномерно располагающихся между 0 и 1. Единица включается!

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [21]:
np.random.random((3, 3)) #массив 3*3, заполненный случайными числами от 0 до 1

array([[0.14838761, 0.87302173, 0.10299558],
       [0.33175822, 0.25096946, 0.19935935],
       [0.6561772 , 0.36899973, 0.10144253]])

In [23]:
np.random.normal(0, 1, (3, 3)) #массив 3*3, случайных чисел по норм распределению с медианой 0 и ст отклон 1

array([[ 0.180645  , -0.71079977,  0.2338106 ],
       [ 1.22010561,  0.59054381, -1.26790155],
       [-1.83930845,  0.54872475,  0.40634649]])

In [25]:
np.random.randint(0, 10, (3, 3)) #массив 3*3 случайных целых чисел от 0 до 10

array([[2, 9, 1],
       [0, 6, 6],
       [2, 8, 2]])

In [27]:
np.eye(3) #единичная матрица 3*3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
np.empty(3) #массив из 3-х целочисленных значений, случайно оказавшиеся в памяти

array([1., 1., 1.])

# Атрибуты массивов библиотеки NumPy

In [31]:
np.random.seed(0) #начальное значение для целей воспроизводимости

In [32]:
x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3, 4))
x3 = np.random.randint(10, size=(3, 4, 5))

In [34]:
print('x3 ndim', x3.ndim) #размерность
print('x3 shape', x3.shape) #размер каждого измерения
print('x3 size', x3.size) # общий размер массива

x3 ndim 3
x3 shape (3, 4, 5)
x3 size 60


In [36]:
x3.dtype #тип данных массива

dtype('int64')

In [37]:
print('x3 itemsize', x3.itemsize, 'bytes') #размер в байтах каждого массива
print('x3 nbytes', x3.nbytes, 'bytes') #полный размер массива в байтах

x3 itemsize 8 bytes
x3 nbytes 480 bytes


In [38]:
print('x3 size * x3 itemsize = x3 nbytes')
print(x3.size*x3.itemsize, '=', x3.nbytes)

x3 size * x3 itemsize = x3 nbytes
480 = 480


# Индексация массива

In [39]:
x1

array([5, 0, 3, 3, 7, 9])

In [40]:
x1[0]

5

In [41]:
x1[4]

7

In [42]:
x1[-1]

9

In [43]:
x1[-2]

7

In [44]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [45]:
x2[0, 0]

3

In [46]:
x2[2, 0]

1

In [47]:
x2[2, -1]

7

In [48]:
x2[0, 0] = 12

In [49]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [52]:
x1[0] = 3.144563 #значение с плавающей точкой будет преобразовано к общему типу массивов

In [53]:
x1

array([3, 0, 3, 3, 7, 9])

# Срезы массивов
## 1.1 Одномерные массивы
### Х[начало:конец:шаг]. По умолчанию x[начало = 0:конец = размер соответст измерения:шаг = 1]

In [68]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
x.dtype

dtype('int64')

In [59]:
x[:5] #первые 5 элементов

array([0, 1, 2, 3, 4])

In [60]:
x[5:] #элементы после индекса 5

array([5, 6, 7, 8, 9])

In [61]:
x[4:7] #подмассив из середины

array([4, 5, 6])

In [62]:
x[::2] #каждый второй элемент

array([0, 2, 4, 6, 8])

In [63]:
x[1::2] #каждый второй элемент, начиная с индекса 1

array([1, 3, 5, 7, 9])

In [64]:
x[::-1] #перевернутый массив

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [65]:
x[5::-2] #каждый второй элемент в обратном порядке, начиная с элемента с индексом 5

array([5, 3, 1])

## 1.2 Многомерные массивы

In [69]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [70]:
x2[:2, :3] #две строки, три столбца

array([[12,  5,  2],
       [ 7,  6,  8]])

In [72]:
x2[:, ::2] #все строки и каждый второй столбец

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [73]:
x2[::-1, ::-1] #перевернутый массив

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

## Доступ к строкам и столбцам массива

In [75]:
x2[:, 0] #первый столбец массива

array([12,  7,  1])

In [78]:
x2[0, :] #первая строка массива

array([12,  5,  2,  4])

In [79]:
x2[0] #эквивалентно x2[0, :]

array([12,  5,  2,  4])

## Массивы в numpy возвращают представления, а не копии как в списках

In [80]:
x2_sub = x2[:2, :2]

In [81]:
x2_sub[0, 0] = 99

In [82]:
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

### Создание копии массива

In [83]:
x2_sub_copy = x2[:2, :2].copy()
x2_sub_copy

array([[99,  5],
       [ 7,  6]])

In [84]:
x2_sub_copy[0, 0] = 42

In [85]:
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [86]:
x2_sub_copy

array([[42,  5],
       [ 7,  6]])

### Изменение формы массива

In [87]:
grid = np.arange(1, 10).reshape((3, 3))

In [88]:
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [89]:
x = np.array([1, 2, 3])

In [91]:
x.reshape(1, 3) #преобразование в вектор-строку

array([[1, 2, 3]])

In [92]:
x[np.newaxis, :] #преобразование в вектор-строку через newaxis

array([[1, 2, 3]])

In [93]:
x.reshape(3, 1) #преобразование в вектор-столбец

array([[1],
       [2],
       [3]])

In [94]:
x[:, np.newaxis] #преобразование в вектор-столбец через newaxis

array([[1],
       [2],
       [3]])

# Слияние и разбиение массивов
## 1.1 Слияние массивов

In [95]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

In [96]:
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [105]:
z = [99, 99, 99]

In [106]:
type(z)

list

In [107]:
np.concatenate([x, y, z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [108]:
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [110]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [111]:
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [113]:
np.concatenate([grid, grid], axis=1) #слияние по второй координате (с индексом 0)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

### Для массивов с различающимися измерениями

In [115]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                [6, 5, 4]])

In [116]:
np.vstack([x, grid]) #объединение по вертикали

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [117]:
y = np.array([[99],
             [99]])

In [120]:
np.hstack([grid, y]) #объединение по горизонтали

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

## Разбиение массивов

In [121]:
x = [1, 2, 3, 99, 99, 3, 2, 1]

In [122]:
x1, x2, x3 = np.split(x, [3, 5])

In [123]:
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [124]:
grid = np.arange(16).reshape((4, 4))

In [125]:
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [126]:
upper, lower = np.vsplit(grid, [2])

In [127]:
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [128]:
left, right = np.hsplit(grid, [2])

In [129]:
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
